"""Data contract for the PV monitoring pipeline.

This module defines the single source of truth for what one photovoltaic
measurement looks like. Every other backend module (``client``,
``data_cleaner``, ``metrics``, ``data_storage``) imports :class:`PVReading`
so that the shape of a reading is defined in exactly one place.

Design principle (store raw, derive on read): only the raw instantaneous
power measurements are stored. Cumulative energy (kWh), self-consumption,
autarky, etc. are *derived* later by the calculation layer and are
deliberately NOT fields here.
"""

from dataclasses import dataclass
from datetime import datetime


@dataclass(frozen=True)
class PVReading:
    """A single photovoltaic measurement taken at one point in time.

    A new instance is produced roughly every 5 seconds, either from the
    university's PV API or from the mock-data generator while that API is
    unavailable. Instances are immutable (``frozen=True``) because a past
    measurement is a fact that must never be mutated.

    All power values are raw instantaneous power measurements (in W)

    Attributes:
        timestamp (datetime): Moment the reading was taken, in UTC.
        pv_power (float): Power currently generated by the panels, in W.
            Always >= 0.
        consumption_power (float): Power currently consumed by the
            building, in W. Always >= 0.
        grid_import_power (float): Power currently drawn from the external
            grid, in W. Always >= 0; equals 0 when the panels cover the
            full load.
    """

    timestamp: datetime
    pv_power: float
    consumption_power: float
    grid_import_power: float
